theme: jekyll-theme-minimal
title: Fadi Helal's homepage
description: Bookmark this to keep an eye on my project updates!
### My Tasks:
- [x] Task Website must be public.
- [x] Task Use at least handful of Github flavour markdown features to format the web page.
- [x] Task Document your work progress with few screenshots to the learning diary.
- [x] Write the Github page address to the learning diary so that your peer reviewers can verify it easily.
- [x] Keep the pages available until you have received your course grade.
Here’s a simple footnote [^1] and you can also read further about Markdown [^references]
[^1]: This is the first footnote.
[^references]: Check further about Cloud Services - 5 ECTS at [CampusOnline.fi](https://tl.oamk.fi/cloudservices/) 
